#print("hello world!")
#print("hello again")
#print("I like typing this.")
print("This is fun.") 
#print("Yay! Printing.")
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print('This is another line for excercise')
# print("this is another line for exercise, this time with a hashtag")